# .streamlit/pages.toml

# Specify the main page (optional, app.py is default)
main_page = "app.py"

# Define the order and properties of your pages
[[pages]]
path = "pages/UAE Hospital Details.py"
title = "ğŸ—ºï¸ Hospital Map" # Custom title
icon = "ğŸ—ºï¸" # Custom icon

[[pages]]
path = "pages/State Cost Income.py"
title = "ğŸ’° Costs & Income Trends"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/Comprehensive Health Data Distribution.py"
title = "ğŸ’° Comprehensive Health Data Distribution"
icon = "ğŸ“ˆ"



[[pages]]
path = "pages/Distribution Charts.py"
title = "ğŸ“Š Data Distributions"
icon = "ğŸ“ˆ"


[[pages]]
path = "pages/Detailed Scatter Plot Analysis.py"
title = "ğŸ–¼ï¸ Scatter Plot"
icon = "ğŸ–¼ï¸"


[[pages]]
path = "pages/Word Cloud.py"
title = "ğŸ–¼ï¸ Word Cloud"
icon = "ğŸ–¼ï¸"

# You can also include pages not in 'pages/' folder if desired
# [[pages]]
# path = "another_page.py"
# title = "Another Page"
# icon = "âœ¨"

# To hide a page from sidebar:
# [[pages]]
# path = "pages/hidden_page.py"
# sidebar = false